### ISSUE TITLE
Permanent link of data Exchange ?

### ISSUE THREAD

**Issue by LiloBzH** [keeweb/keeweb-connect#6]
Hi

I suppose this is not a bug because we can read in app :

"Settings you select here are valid only for the active session. You can view and manage sessions in KeeWeb settings."

But, if i restarted Chrome, Session is closed . Each Restart of chrome, link session is closed ?

Is this normal? An improvement in the future?

**Comment by antelle** [comment]
This is expected. Unfortunately, browser extensions can't store data securely, so that any app can read data from KeeWeb this way.

To make it easier, everything is optimized to pass this screen as quickly as possible:
- the config you select there is saved and options are pre-selected for you next time
- you can hit Enter to approve the request

**Comment by LiloBzH** [comment]
ok ! :-)
